name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  

flutter:
  uses-material-design: true

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset:  assets/fonts/MyFlutterApp.ttf

    
